version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - rubygems
    reviewers:
      - get-bridge/oberbaum

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - github_actions
    reviewers:
      - get-bridge/oberbaum
