AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
  EnforcedStyleForMultiline: "consistent_comma"
Style/TrailingCommaInArguments:
  Enabled: false
  EnforcedStyleForMultiline: "consistent_comma"
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "consistent_comma"
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect
  Exclude:
    - "spec/**/*"
    - "Gemfile"
Layout/MultilineBlockLayout:
  Exclude:
    - "spec/**/*"
Layout/BlockEndNewline:
  Exclude:
    - "spec/**/*"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "scorm_engine.gemspec"
Style/StringLiteralsInInterpolation:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Metrics/AbcSize:
  Max: 50
Style/EachWithObject:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
