sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.8
before_install: gem install bundler
before_script:
  - bundle exec rubocop
  - bundle exec yard doc --fail-on-warning  --no-save --no-output
env:
  global:
    - SCORM_ENGINE_HOST=scorm.engine.net
    - SCORM_ENGINE_USERNAME=username
    - SCORM_ENGINE_PASSWORD=password
    - SCORM_ENGINE_IS_AVAILABLE=false
