name: 'ScormEngine'

on:
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for more details.
  # Using pull_request_target in order to grant dependabot access to run the test action.
  pull_request_target:
    branches-ignore:
      - 'gh-pages'
    types: [labeled] # for dependabot
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
    inputs:
      deploy:
        description: 'Deploy: [true, false]'
        required: true
        default: 'false'

# ensure only one workflow per ref
# pull_request_target/push events commonly result in duplicate workflows being ran
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: >
      contains(github.event.pull_request.labels.*.name, 'dependencies')
      || github.event_name == 'push'
      || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest # currently ubuntu-22.04
          - ubuntu-20.04
          - macos-latest # currently macos-12
          - macos-11
        ruby:
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - head
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.144.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Rubocop
        run: bin/rake rubocop
      - name: Rspec tests
        run: bin/rake spec
      - name: Yard documents
        run: bin/rake yard

  deploy:
    needs: 'tests'
    if: (github.event_name == 'push' || github.event.inputs.deploy == 'true') && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.144.0
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Yard documents
        run: bin/rake yard

      - name: Deploy pages
        if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          SSH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc
          CLEAN: true
          CLEAN_EXCLUDE: '[".gitattributes", ".gitignore", "CNAME", "LICENSE"]'

      # - name: Release new gem
      #   if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
      #   run: |
      #     rake release[remote]
