name: 'ScormEngine'

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
    inputs:
      deploy:
        description: 'Deploy: [true, false]'
        required: true
        default: 'false'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', 2.7, 3.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gems-

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: |
          bundle exec rake rubocop

      - name: Rspec tests
        run: |
          bundle exec rake spec

      - name: Yard documents
        run: |
          bundle exec rake yard

  deploy:
    needs: 'tests'
    if: (github.event_name == 'push' || github.event.inputs.deploy == 'true') && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      # v2.3.4
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Yard documents
        run: |
          bundle exec rake yard

      - name: Deploy pages
        if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc
          CLEAN: true
          CLEAN_EXCLUDE: '[".gitattributes", ".gitignore", "CNAME", "LICENSE"]'

      #- name: Release new gem
        #if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
        #run: |
          #rake release[remote]
