name: 'ScormEngine'

on:
  pull_request:
    types: [labeled]
    branches-ignore:
      - 'gh-pages'
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'
  workflow_dispatch:
    branches-ignore:
      - 'gh-pages'
    inputs:
      deploy:
        description: 'Deploy: [true, false]'
        required: true
        default: 'false'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - head
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Rubocop
        run: bin/rake rubocop
      - name: Rspec tests
        run: bin/rake spec
      - name: Yard documents
        run: bin/rake yard

  deploy:
    needs: 'tests'
    if: (github.event_name == 'push' || github.event.inputs.deploy == 'true') && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Yard documents
        run: bin/rake yard

      - name: Deploy pages
        if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc
          CLEAN: true
          CLEAN_EXCLUDE: '[".gitattributes", ".gitignore", "CNAME", "LICENSE"]'

      # - name: Release new gem
      #   if: (github.event_name == 'push' || github.event.inputs.deploy == 'true')
      #   run: |
      #     rake release[remote]
