name: Publish to GitHub Gems

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version is not needed with a .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build scorm_engine.gemspec

      - name: Publish to GitHub Packages
        env:
          GEM_HOST_API_KEY: ${{ secrets.GIT_HUB_PACKAGES_TOKEN }}
        run: |
          gem push --host https://rubygems.pkg.github.com/get-bridge *.gem